[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
cmds = ["python3 -m pip install -r edgar-api/requirements.txt"]

[start]
cmd = "cd edgar-api && uvicorn main:app --host 0.0.0.0 --port $PORT"
